openapi: 3.0.0
info:
  version: '0.1'
  title: OBapp
  description: |
    OBapp reference point.  
    © 2024, UIC.  
    All rights reserved.
externalDocs:
  description: OBapp reference point
  url: https://uic.org/rail-system/telecoms-signalling/frmcs
servers:
  - url: '{apiRoot}/obapp/v1'
    variables:
      apiRoot:
        default: https://uic.org
        description: apiRoot as defined in clause x.y of UIC FFFIS xyz
paths:
  /registrations:
    post:
      summary: Registration of an application
      operationId: CreateRegistration
      parameters:
        - name: Content-Encoding
          in: header
          description: Content-Encoding, described in IETF RFC 9110
          schema:
            type: string
        - name: Accept-Encoding
          in: header
          description: Accept-Encoding, described in IETF RFC 9110
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
        required: true
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationData'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
  /sessions:
    get:
      summary: get session status for all sessions for all applications
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsData'
  /sessions/{dynamicId}/{sessionId}:
    get:
      summary: get session status for a given sessions for a given application
      parameters:
        - name: dynamicId
          in: path
          description: Unique ID of the application
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
        - name: sessionId
          in: path
          description: Unique ID of the sesson
          required: true
          schema:
            $ref: '#/components/schemas/SessionId'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionData'
components:
  responses:
    '400':
      description: Ill-formed request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    '401':
      description: Not registered
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    '403':
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    '404':
      description: Invalid resource
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
  schemas:
    DynamicId:
      type: string
      format: uuid
      description: >
        String uniquely identifying a application. The format shall be a 
        Universally Unique Identifier (UUID) version 4, as described in IETF RFC
        4122. 
    SessionId:
      type: string
      format: uuid
      description: >
        String uniquely identifying a session. The format shall be a 
        Universally Unique Identifier (UUID) version 4, as described in IETF RFC
        4122. 
    CouplingMode:
      description: application coupling mode
      enum:
        - loose
        - tight
      default: loose
    RegistrationRequest:
      description: Application registration request.
      type: object
      properties:
        appCategory:
          type: string
        staticIdentifier:
          type: string
        dynamicIdentifier:
          type: string
        supportedVersions:
          type: array
          items:
            type: string
        couplingMode:
          $ref: '#/components/schemas/CouplingMode'
    RegistrationData:
      description: Application registration data.
      type: object
      properties:
        registrationStatus:
          enum:
            - registered
            - notRegistered
          default: notRegistered
        selectedVersion:
          type: string
    SessionsData:
      description: session status for several sessions
      type: object
      properties:
        sessionsData:
          type: array
          items:
            $ref: '#/components/schemas/SessionData'
    SessionData:
      description: session status for a specific session
      type: object
      properties:
        dynamicIdentifier:
          type: string
        participants:
          type: array
          items:
            $ref: '#/components/schemas/Uri'
        progressStatus:
          $ref: '#/components/schemas/SessionProgressStatus'
    SessionProgressStatus:
      description: possible status for a session
      enum:
        - established
        - inProgress
        - networkNotReady
        - notRegistered
        - rejected
        - closing
        - closed
    ProblemDetails:
      description: Provides additional information in an error response.
      type: object
      properties:
        type:
          $ref: '#/components/schemas/Uri'
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
          description: >-
            A human-readable explanation specific to this occurrence of the
            problem.
        instance:
          $ref: '#/components/schemas/Uri'
        cause:
          type: string
          description: >
            A machine-readable application error cause specific to this
            occurrence of the problem.  This IE should be present and provide
            application-related error information, if available.
        supportedApiVersions:
          type: array
          items:
            type: string
          minItems: 1
    Uri:
      type: string
      description: String providing an URI formatted according to RFC 3986.
