openapi: 3.0.0
info:
  version: '0.1'
  title: OBapp
  description: |
    OBapp reference point.  
    © 2024, UIC.  
    All rights reserved.
externalDocs:
  description: OBapp reference point
  url: https://uic.org/rail-system/telecoms-signalling/frmcs
servers:
  - url: '{apiRoot}/obapp/v1'
    variables:
      apiRoot:
        default: https://uic.org
        description: apiRoot as defined in clause x.y of UIC FFFIS xyz
        
paths:
  /registrations:
    get:
      summary: Get registrations
      responses:
        '200':
          description: A list of registrations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Create a new registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                registration_id:
                  type: string
              required:
                - registration_id
      responses:
        '201':
          description: Created
        '400':
          description: Bad request

  /registrations/{DynamicId}:
    get:
      summary: Get a registration by ID
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
    delete:
      summary: Delete a registration by ID
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content

  /sessions:
    get:
      summary: Get sessions
      responses:
        '200':
          description: A list of sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Create a new session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
              required:
                - session_id
      responses:
        '201':
          description: Created
        '400':
          description: Bad request

  /sessions/{DynamicId}:
    get:
      summary: Get a session by ID
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
    post:
      summary: Update a session by ID
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
              required:
                - session_id
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
    delete:
      summary: Delete a session by ID
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content

  /sessions/{DynamicId}/{SessionId}:
    get:
      summary: Get a session by ID and Session ID
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
        - name: SessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
    put:
      summary: Update a session by ID and Session ID
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
        - name: SessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
              required:
                - session_id
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
    delete:
      summary: Delete a session by ID and Session ID
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
        - name: SessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content

  /notifications:
    get:
      summary: Get notifications
      responses:
        '200':
          description: A list of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    delete:
      summary: Delete all notifications
      responses:
        '204':
          description: No content

  /notifications/general:
    get:
      summary: Get general notifications
      responses:
        '200':
          description: A list of general notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    delete:
      summary: Delete all general notifications
      responses:
        '204':
          description: No content

  /notifications/{DynamicId}/{Channel}:
    get:
      summary: Get notifications by DynamicId and Channel
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
        - name: Channel
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    delete:
      summary: Delete notifications by DynamicId and Channel
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
        - name: Channel
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
