openapi: 3.0.0
info:
  version: '0.1'
  title: OBapp
  description: |
    OBapp reference point.  
    © International Union of Railways (UIC) – Paris, 2024 
externalDocs:
  description: OBapp reference point
  url: https://uic.org/rail-system/telecoms-signalling/frmcs
servers:
  - url: '{apiRoot}/obapp/v1'
    variables:
      apiRoot:
        default: https://uic.org
        description: apiRoot as defined in clause x.y of UIC FFFIS xyz
paths:
  /registrations:
    get:
      summary: List of registrations
      responses:
        '200':
          description: A list of registrations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Register an application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                registration_id:
                  type: string
              required:
                - registration_id
      responses:
        '201':
          description: Created
          headers:
            Location:
              description: 'Contains the URI of the newly created resource'
              required: true
              schema:
                type: string
        '400':
          description: Bad request

  /registrations/{DynamicId}:
    get:
      summary: Get information on an application registration
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
    delete:
      summary: De-register an application
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content

  /sessions:
    get:
      summary: Get sessions
      responses:
        '200':
          description: List of sessions for all applications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /sessions/{DynamicId}:
    get:
      summary: List of sessions for an application
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
    post:
      summary: Create a session for an application
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
              required:
                - session_id
      responses:
        '201':
          description: 'Session created'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource'
              required: true
              schema:
                type: string
        '400':
          description: Bad request
    delete:
      summary: Terminate all sessions for an application
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content

  /sessions/{DynamicId}/{SessionId}:
    get:
      summary: Get information on a session of an application
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
        - name: SessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
    put:
      summary: Accept an incoming session for an application
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
        - name: SessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
              required:
                - session_id
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
    delete:
      summary: Terminate a session for an application
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
        - name: SessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content

  /notifications:
    get:
      summary: List of subscriptions for all applications
      responses:
        '200':
          description: A list of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    delete:
      summary: Unsubscribe all subscriptions
      responses:
        '204':
          description: No content

  /notifications/general:
    get:
      summary: Get general notifications
      responses:
        '200':
          description: Subscribe to the general notification channel
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    delete:
      summary: Unsubscribe all subscriptions to the general notification channel
      responses:
        '204':
          description: No content

  /notifications/{DynamicId}/{Channel}:
    get:
      summary: Subscribe to a specific channel for an application
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
        - name: Channel
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    delete:
      summary: Unsubscribe to a specific channel for an application
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            type: string
        - name: Channel
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content

components:
  schemas:
    # FFFIS application and session identifiers
    # need to specify the version of UUID that shall be used
    dynamicId:
      description: "identifier of the application instance, dynamically assigned at registration. UUID."
      type: string
      format: uuid
    sessionId:
      description: "identifier of the application session. UUID"
      type: string
      format: uuid

    # IPv4 / IPv6 addresses
    # Aligned with 3GPP 29.571 Common Data yaml description
    Ipv4Addr:
      description: String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
      type: string
      pattern: '^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$'
      example: '198.51.100.1'
    Ipv6Addr:
      description: String identifying an IPv6 address formatted according to clause 4 of RFC5952.
      type: string
      allOf:
        - pattern: '^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$'
        - pattern: '^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$'
      example: '2001:db8:85a3::8a2e:370:7334'

    # IP address
    # Similar to 3GPP 29.571 Common Data yaml description (without ipv6Prefix which is not applicable in FRMCS FFFIS)
    IpAddr:
      description: Contains an IP adress.
      type: object
      oneOf:
        - required:
          - ipv4Addr
        - required:
          - ipv6Addr
      properties:
        ipv4Addr:
          $ref: '#/components/schemas/Ipv4Addr'
        ipv6Addr:
          $ref: '#/components/schemas/Ipv6Addr'

    # URI, aligned with 3GPP 29.571 Common Data yaml description
    Uri:
      description: String providing an URI formatted according to RFC 3986.
      type: string
      
    # FQDN, aligned with 3GPP 29.571 Common Data yaml description
    Fqdn:
      description: Fully Qualified Domain Name
      type: string
      pattern: '^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\.)+[A-Za-z]{2,63}\.?$'
      minLength: 4
      maxLength: 253

    # FFFIS enums
    CouplingMode:
      description: |
        Possible values:
          - tight for Tight Coupled mode
          - loose for Loose Coupled mode
      type: string
      enum:
        - tight
        - loose
      default: loose
